server:
  port: 2333
  address: 0.0.0.0

lavalink:
  server:
    password: "youshallnotpass" # Debe coincidir con tu .env
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false
    filters: # Permite ecualización y efectos
      volume: true
      equalizer: true
      karaoke: true
      timescale: true
      tremolo: true
      vibrato: true
      distortion: true
      rotation: true
      channelMix: true
      lowPass: true
    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    opusEncodingQuality: 10
    resamplingQuality: LOW
    trackStuckThresholdMs: 10000
    useSeekGhosting: true
    youtubePlaylistLoadLimit: 6
    playerUpdateInterval: 5

metrics:
  prometheus:
    enabled: false

logging:
  level:
    root: INFO
    lavalink: INFO

  request:
    enabled: false

plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    # Si te bloquean, aquí es donde pondríamos las "cookies" más adelante